name: app_with_apps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  provider: ^6.0.5

dev_dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_lints: ^2.0.2
  flutter_localization: ^0.1.14
  flutter_test:
    sdk: flutter
  http: any
  intl: ^0.18.0
  rive: ^0.12.1

flutter:
  assets:
      - assets/animation/

  uses-material-design: true
